version: "2.4"

services:
  
  mssql-init-sfe:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-xm1-mssql-init-sfe:${SFE_VERSION}-${SITECORE_VERSION}
    build:
      context: ./docker/build/mssql-init
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}sitecore-xm1-mssql-init:${SITECORE_VERSION}
        MODULE_ASSETS: bverdonck/sitecore-forms-extensions-assets:${SFE_VERSION}
        MODULE_NAME: sfe  
    scale: 0

